### ISSUE TITLE
Rollup failed to resolve import "postcss-nesting"

### ISSUE THREAD

**Issue by quantuminformation** [dominikg/svite#10]
## Description
I basically copied over the relevant parts from the tailwind example, when running `npm run dev` I get

gives
```
[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "postcss-nesting" from "node_modules/postcss-preset-env/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
Error: [vite]: Rollup failed to resolve import "postcss-nesting" from "node_modules/postcss-preset-env/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
```

![image](https://user-images.githubusercontent.com/216566/86795986-6912d980-c06e-11ea-8570-377b664eef6f.png)

## Reproduction

https://github.com/quantuminformation/mentorcv

## Additional Information

- operating system
Osx
- versions for
  - node 12
  - npm 6.12.1
  - svite latest 
  - vite vite v1.0.0-beta.11
  - svelte ^3.23.2
- logs
  - use logLevel: 'debug' in svite config
  - start vite with `vite --debug` flag

```
 mentorcv git:(master) ✗ npm run dev

> svelte-app@1.0.0 dev /Users/nikos/WebstormProjects/mentorcv
> vite --debug

vite v1.0.0-beta.11
  vite:config env mode: development +0ms
[dotenv][DEBUG] did not match key and value when parsing line 9:
[dotenv][DEBUG] did not match key and value when parsing line 10:
[dotenv][DEBUG] did not match key and value when parsing line 11:
  vite:config env: {} +2ms
  vite:config config resolved in 53ms +1ms
[svite] applied changes to svelte config used for dev.
{ css: true, emitCss: false }
  vite:resolve (node_module entry) firebase -> dist/index.esm.js +0ms
  vite:optimize optimizing firebase (imports sub dependencies) +0ms
  vite:resolve (node_module entry) query-string -> undefined +1ms
  vite:optimize skipping query-string (cannot resolve entry) +0ms
/Users/nikos/WebstormProjects/mentorcv query-string
[vite] cannot resolve entry for dependency query-string.
  vite:resolve (node_module entry) svelte-loading-spinners -> dist/index.mjs +1ms
  vite:optimize skipping svelte-loading-spinners (single esm file, doesn't need optimization) +4ms
  vite:resolve (node_module entry) svelte-routing -> src/index.js +4ms
  vite:optimize optimizing svelte-routing (contains relative imports) +2ms
  vite:resolve (node_module entry) svelte-spinner -> dist/index.mjs +2ms
  vite:optimize optimizing svelte-spinner (imports sub dependencies) +1ms
  vite:resolve (node_module entry) postcss-import -> undefined +1ms
  vite:optimize skipping postcss-import (cannot resolve entry) +1ms
/Users/nikos/WebstormProjects/mentorcv postcss-import
[vite] cannot resolve entry for dependency postcss-import.
  vite:resolve (node_module entry) postcss-load-config -> src/index.js +0ms
  vite:optimize optimizing postcss-load-config (no exports, likely commonjs) +0ms
  vite:resolve (node_module entry) postcss-preset-env -> index.mjs +3ms
  vite:optimize optimizing postcss-preset-env (imports sub dependencies) +3ms
  vite:resolve (node_module entry) svelte-preprocess -> dist/index.js +1ms
  vite:optimize optimizing svelte-preprocess (no exports, likely commonjs) +1ms
  vite:resolve (node_module entry) svite -> index.js +1ms
  vite:optimize optimizing svite (no exports, likely commonjs) +1ms
  vite:optimize skipping tailwindcss (internal excluded) +0ms
  vite:optimize skipping vite (internal excluded) +0ms
  vite:resolve (node_module entry) svelte/animate -> ./index.mjs +0ms
  vite:resolve (node_module entry) svelte/easing -> ./index.mjs +1ms
  vite:resolve (node_module entry) svelte/internal -> ./index.mjs +0ms
  vite:resolve (node_module entry) svelte/motion -> ./index.mjs +0ms
  vite:resolve (node_module entry) svelte/store -> ./index.mjs +1ms
  vite:resolve (node_module entry) svelte/transition -> ./index.mjs +0ms
  vite:resolve (node_module entry) svelte -> index.mjs +0ms
  vite:resolve failed to resolve package.json for svelte-hmr/runtime/esm +1ms
  vite:resolve failed to resolve package.json for svelte-hmr/runtime/proxy-adapter-dom +8ms
  vite:resolve failed to resolve package.json for svelte-hmr/runtime/hot-api-esm +0ms
[vite] Optimizable dependencies detected:
firebase, svelte-routing, svelte-spinner, postcss-load-config, postcss-preset-env, svelte-preprocess, svite, svelte/animate, svelte/easing, svelte/internal, svelte/motion, svelte/store, svelte/transition, svelte, svelte-hmr/runtime/proxy-adapter-dom, svelte-hmr/runtime/hot-api-esm
Pre-bundling them to speed up dev server page load...
(this will be run only when your dependencies have changed)

[vite] Dep optimization failed with error:
[vite]: Rollup failed to resolve import "postcss-nesting" from "node_modules/postcss-preset-env/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
Error: [vite]: Rollup failed to resolve import "postcss-nesting" from "node_modules/postcss-preset-env/index.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`rollupInputOptions.external`
    at Object.onwarn (/Users/nikos/WebstormProjects/mentorcv/node_modules/vite/dist/node/build/index.js:68:19)
    at Object.onwarn (/Users/nikos/WebstormProjects/mentorcv/node_modules/rollup/dist/shared/rollup.js:18957:20)
    at ModuleLoader.handleResolveId (/Users/nikos/WebstormProjects/mentorcv/node_modules/rollup/dist/shared/rollup.js:17847:26)
    at /Users/nikos/WebstormProjects/mentorcv/node_modules/rollup/dist/shared/rollup.js:17837:22
    at async Promise.all (index 27)
    at ModuleLoader.fetchStaticDependencies (/Users/nikos/WebstormProjects/mentorcv/node_modules/rollup/dist/shared/rollup.js:17835:34)
    at async Promise.all (index 0)
    at ModuleLoader.fetchModule (/Users/nikos/WebstormProjects/mentorcv/node_modules/rollup/dist/shared/rollup.js:17812:9)
    at async Promise.all (index 4) {
  watchFiles: [
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/postcss-preset-env/index.mjs',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svite/index.js',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svelte/index.mjs',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svelte/animate/index.mjs',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svelte/internal/index.mjs',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svelte/easing/index.mjs',
    '/Users/nikos/WebstormProjects/mentorcv/node_modules/svelte/motion/index.mjs',```

**Comment by quantuminformation** [comment]
Update I've moved things around into devdependencies and now get this

```
[vite] Dep optimization failed with error:
Dependency rollup-plugin-svelte-hot is attempting to import Node built-in module path.
This will not work in a browser environment.
Imported by: node_modules/rollup-plugin-svelte-hot/index.js```

**Comment by dominikg** [comment]
svite, vite, and svelte-preprocess all need to be in devdependencies.

You also need to put an 'index.html' file at the project root that includes a `<script type="module">` tag referencing your main.js which creates and mounts App.svelte.

The 'public' directory should only contain files never referenced by your source directly. See https://github.com/vitejs/vite#the-public-directory

Please check https://github.com/dominikg/svite/tree/master/examples/postcss-tailwind for reference
