### ISSUE TITLE
Parse error: Object.parse (node_modules/es-module-lexer/dist/lexer.cjs:1:406)

### ISSUE THREAD

**Issue by bfanger** [dominikg/svite#44]
After installing `svelte-spa-router` i got an error when running `npm run dev`:

```Error: Parse error
    at Object.parse ($project/node_modules/es-module-lexer/dist/lexer.cjs:1:406)
    at $project/node_modules/vite/dist/node/optimizer/index.js:234:54
    at Array.filter (<anonymous>)
    at resolveQualifiedDeps ($project/node_modules/vite/dist/node/optimizer/index.js:199:32)
    at Object.optimizeDeps ($project/node_modules/vite/dist/node/optimizer/index.js:64:37)
    at async Server.server.listen ($project/node_modules/vite/dist/node/server/index.js:89:13)
    at async runServe ($project/node_modules/svite/bin/svite.js:148:3)
    at async Command.<anonymous> ($project/node_modules/svite/bin/svite.js:378:7)
    at async Promise.all (index 0)
    at async main ($project/node_modules/svite/bin/svite.js:476:3)
  ```

Looks like the vite optimizer is unable to handle dependancies containing `*.svelte` files.

Creating a `vite.config.js` with:

```js
module.exports = {
    optimizeDeps: {
      exclude: ['svelte-spa-router'],
    },
  };
```

Solved the issue.

It would be nice if svite could detect this error and provide a "use optimizeDeps for x in vite.config.js" hint, or disable the optimization automatically.

**Comment by quantuminformation** [comment]
I think i started seeing this after v 0.5, so i stayed on 0.4.1 atm

**Comment by dominikg** [comment]
svelte-spa-router uses .svelte extension in "main" and "svelte" fields of its package.json. 
I don't think thats a valid use for those fields. These should point to an index.js file exporting whats needed.
see https://github.com/sveltejs/component-template/blob/master/package.json  
I'm actually surprised this worked before

**Comment by dominikg** [comment]
Change that introduced this bug: https://github.com/dominikg/svite/commit/7677bdf9fc333756090f85aae0a637dfcdd99984

the option "resolveSvelteExtensions" leads to vite optimize no longer ignoring .svelte references in package.json.
You can set it to false via vite.config.js if you have  svite plugin configured there via `svite({resolveSvelteExtensions: false})` alternatively you can pass it via cli `svite dev --resolveSvelteExtensions ''`   note that the empty string is on purpose to avoid #45 

both bugs are going to be fixed this week. sorry for the inconvenience
